# Generated by Django 5.0.2 on 2025-10-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='nickname',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default='Candidate', max_length=80),
        ),
    ]
