# Generated by Django 5.0.2 on 2025-10-11 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0003_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='phone_number',
            field=models.CharField(help_text='Phone number in international format: +[country code][number]', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format: +[country code][number] (e.g., +1234567890)', regex='^\\+\\d{1,3}\\d{4,14}$')]),
        ),
    ]
