# Generated by Django 5.0.2 on 2025-10-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0004_alter_voter_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_title', models.CharField(default='Porpon Young Generation Chairman and Lady Election', max_length=200)),
                ('election_description', models.TextField(default='Vote for your preferred candidate for the position of Chairman and Lady')),
                ('start_time', models.DateTimeField(blank=True, help_text='When voting starts', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='When voting ends', null=True)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for the election (e.g., UTC, America/New_York, Africa/Freetown)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is voting currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Election Settings',
                'verbose_name_plural': 'Election Settings',
            },
        ),
    ]
